# Generated by Django 6.0.5 on 2026-05-08 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField(max_length=1000)),
                ('category', models.CharField(choices=[('gratitude', 'Unsent gratitude'), ('recognition', 'Moment of recognition'), ('almost_friend', 'Almost friend'), ('hope_okay', "I hope you're okay"), ('door_open', 'A door left open')], max_length=40)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('approximate_location_label', models.CharField(blank=True, help_text='Example: near the station, outside the library, Kelham Island', max_length=120)),
                ('door_left_open', models.BooleanField(default=False)),
                ('reconnection_note', models.TextField(blank=True, help_text='Optional. A gentle note only, not identifying information.', max_length=500)),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
